FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o user ./cmd/user/

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/user /usr/local/bin/
COPY --from=builder /app/configs/user.yaml /etc/sankaer/user.yaml
EXPOSE 8082
CMD ["user", "-config", "/etc/sankaer/user.yaml"]
